/* Signal Labs | Signal Schedule | schedule/pages/workspace/builder.js | v5.1.0 */
const state={settings:null,data:null,availability:null,loadedSchedule:null,lastValidation:null};
const $=(s)=>document.querySelector(s);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
Promise.all([fetch('data/schedule-admin-settings.json').then(r=>r.json()),fetch('data/schedule-builder-sandbox.json').then(r=>r.json()),fetch('data/employee-availability-preferences-preview.json').then(r=>r.json()).catch(()=>null)]).then(([settings,data,availability])=>{state.settings=settings;state.data=data;state.availability=availability;applySavedHandoff();render();});
function applySavedHandoff(){
  const raw=localStorage.getItem('signalScheduleBuilderLoad');
  if(!raw)return;
  try{
    const saved=JSON.parse(raw);
    if(saved?.payload?.settings)state.settings={...state.settings,...saved.payload.settings};
    if(Array.isArray(saved?.payload?.assignments))state.data.assignments=saved.payload.assignments.map(a=>({day:a.day,role:a.role,shift:a.shift,employee:a.employee}));
    state.loadedSchedule=saved;
    setSaveStatus(`Loaded snapshot: ${saved.name || saved.id}`);
  }catch(error){setSaveStatus(`Snapshot handoff could not be loaded: ${error.message}`);}finally{localStorage.removeItem('signalScheduleBuilderLoad');}
}
function render(){renderSettings();renderGrid();renderEmployees();renderEmployeeDatalist();validate();document.querySelectorAll('[data-builder-action]').forEach(b=>b.addEventListener('click',onAction));}
function renderSettings(){const el=$('[data-builder-settings]');const s=state.settings;el.innerHTML=`${field('Agency name','agency.name',s.agency.name)}${field('Week starts','agency.weekStart',s.agency.weekStart)}${field('Pay period starts','agency.payPeriodStart',s.agency.payPeriodStart)}${field('Time format','agency.timeFormat',s.agency.timeFormat)}${field('Time off increment minutes','requestRules.timeOffIncrementMinutes',s.requestRules.timeOffIncrementMinutes)}${field('OT increment minutes','requestRules.overtimeIncrementMinutes',s.requestRules.overtimeIncrementMinutes)}`;el.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{setPath(i.dataset.path,i.value);validate();}));}
function field(label,path,value){return `<label class="builder-field"><span>${esc(label)}</span><input data-path="${esc(path)}" value="${esc(value)}"></label>`}
function setPath(path,value){const parts=path.split('.');let obj=state.settings;while(parts.length>1)obj=obj[parts.shift()];obj[parts[0]]=value;}
function renderGrid(){const grid=$('[data-builder-grid]');const days=state.data.days;const rows=[];state.settings.coverageRules.forEach(rule=>{rows.push({role:rule.role,shift:rule.shift,minimum:Number(rule.minimum),maximum:Number(rule.maximum)});});grid.querySelector('thead').innerHTML=`<tr><th>Role / shift</th>${days.map(d=>`<th>${d}</th>`).join('')}</tr>`;grid.querySelector('tbody').innerHTML=rows.map(row=>`<tr data-row-role="${esc(row.role)}" data-row-shift="${esc(row.shift)}"><th><strong>${esc(row.role)}</strong><span class="builder-chip">${esc(row.shift)} min ${row.minimum}</span></th>${days.map(day=>cell(day,row)).join('')}</tr>`).join('');grid.querySelectorAll('input[data-assignment]').forEach(i=>{i.setAttribute('list','builderEmployeeOptions');i.addEventListener('input',()=>{showAssignmentHint(i);validate();});i.addEventListener('focus',()=>showAssignmentHint(i));});}
function cell(day,row){const matches=state.data.assignments.filter(a=>a.day===day&&a.role===row.role&&a.shift===row.shift);const count=Math.max(row.minimum,matches.length,1);let inputs='';for(let i=0;i<count;i++){const val=matches[i]?.employee||'';inputs+=`<input data-assignment data-day="${esc(day)}" data-role="${esc(row.role)}" data-shift="${esc(row.shift)}" value="${esc(val)}" placeholder="Employee or OPEN">`;}return `<td><div class="builder-cell">${inputs}</div></td>`;}
function renderEmployees(){const el=$('[data-builder-employees]');el.innerHTML=state.data.employees.map(e=>`<div class="builder-employee"><strong>${esc(e.name)}</strong><span>${esc(e.role)} • ${esc(e.group)}</span><span>${esc(e.quals.join(', '))}</span></div>`).join('');}
function readAssignments(){return Array.from(document.querySelectorAll('input[data-assignment]')).map(i=>({day:i.dataset.day,role:i.dataset.role,shift:i.dataset.shift,employee:i.value.trim()}));}
function validate(){const assignments=readAssignments();const results=[];let open=0,short=0,over=0,conflicts=0,hours={};document.querySelectorAll('input[data-assignment]').forEach(i=>{i.classList.remove('is-open','is-conflict')});for(const rule of state.settings.coverageRules){for(const day of state.data.days){const cells=assignments.filter(a=>a.day===day&&a.role===rule.role&&a.shift===rule.shift&&a.employee);const real=cells.filter(a=>a.employee.toUpperCase()!=='OPEN');const openCells=cells.filter(a=>a.employee.toUpperCase()==='OPEN');open+=openCells.length;if(real.length<Number(rule.minimum)){short++;results.push({type:'bad',title:`Short ${rule.role} ${rule.shift} on ${day}`,body:`Need ${rule.minimum}; assigned ${real.length}.`});}if(real.length>Number(rule.maximum)){over++;results.push({type:'warn',title:`Over max ${rule.role} ${rule.shift} on ${day}`,body:`Max ${rule.maximum}; assigned ${real.length}.`});}real.forEach(a=>{hours[a.employee]=(hours[a.employee]||0)+12;const unavailable=state.data.unavailable.find(u=>u.day===a.day&&u.employee.toLowerCase()===a.employee.toLowerCase());if(unavailable){conflicts++;results.push({type:'bad',title:`Unavailable conflict: ${a.employee}`,body:`${day} ${a.shift}: ${unavailable.reason}`});}});}}
document.querySelectorAll('input[data-assignment]').forEach(i=>{if(i.value.trim().toUpperCase()==='OPEN')i.classList.add('is-open');const bad=state.data.unavailable.find(u=>u.day===i.dataset.day&&u.employee.toLowerCase()===i.value.trim().toLowerCase());if(bad)i.classList.add('is-conflict');});
state.lastValidation={short,open,conflicts,over,hours,results,validatedAt:new Date().toISOString()};
const summary=$('[data-builder-summary]');summary.innerHTML=`<span class="builder-chip ${short?'builder-chip--bad':'builder-chip--good'}">${short} short</span><span class="builder-chip ${open?'builder-chip--warn':'builder-chip--good'}">${open} open</span><span class="builder-chip ${conflicts?'builder-chip--bad':'builder-chip--good'}">${conflicts} conflicts</span><span class="builder-chip ${over?'builder-chip--warn':'builder-chip--good'}">${over} over max</span>`;
const res=$('[data-builder-results]');const hourRows=Object.entries(hours).sort((a,b)=>b[1]-a[1]).map(([n,h])=>`<div class="builder-result"><strong>${esc(n)}</strong>${h} scheduled hours this week</div>`).join('');res.innerHTML=(results.length?results.map(r=>`<div class="builder-result"><strong>${esc(r.title)}</strong><span>${esc(r.body)}</span></div>`).join(''):'<div class="builder-result"><strong>No blocking warnings</strong><span>Current assignments meet the configured minimums and availability checks.</span></div>')+`<h3>Weekly Hours</h3>${hourRows}`;return state.lastValidation;}
function onAction(e){const action=e.currentTarget.dataset.builderAction;if(action==='validate')validate();if(action==='save')saveDraft();if(action==='sample')location.reload();if(action==='clear'){document.querySelectorAll('input[data-assignment]').forEach(i=>i.value='');validate();}}
function buildPayload(){const validation=validate();const cleanAssignments=readAssignments().filter(a=>a.employee);return {agencyId:'agency-central-dispatch',name:`${state.settings.agency.name || 'Schedule'} Snapshot ${new Date().toLocaleDateString()}`,status:'draft',scheduleStartDate:state.data.scheduleStartDate || '2026-06-15',scheduleEndDate:state.data.scheduleEndDate || '2026-06-21',source:'builder',payload:{settings:state.settings,assignments:cleanAssignments,employees:state.data.employees,days:state.data.days},validationSummary:validation,updatedBy:'browser-builder'};}
async function saveDraft(){
  const adminKey=window.prompt('Enter ADMIN_API_KEY to save this protected schedule snapshot.');
  if(!adminKey){setSaveStatus('Save cancelled. Protected snapshot writes require ADMIN_API_KEY.');return;}
  const body=buildPayload();
  setSaveStatus('Saving schedule snapshot…');
  try{
    const res=await fetch('/api/saved-schedules',{method:'POST',headers:{'content-type':'application/json','x-admin-api-key':adminKey},body:JSON.stringify(body)});
    const json=await res.json().catch(()=>({ok:false,errors:[{message:'API returned non-JSON response.'}]}));
    if(!res.ok||!json.ok){const message=(json.errors||[]).map(e=>e.message).join(' ')||`HTTP ${res.status}`;setSaveStatus(`Save failed: ${message}`);return;}
    state.loadedSchedule=json.data;setSaveStatus(`Saved snapshot: ${json.data.name} (${json.data.id})`);
  }catch(error){setSaveStatus(`Save failed: ${error.message}`);}
}
function setSaveStatus(text){const el=$('[data-builder-save-status]');if(el)el.textContent=text;}
function renderEmployeeDatalist(){let dl=document.getElementById('builderEmployeeOptions');if(!dl){dl=document.createElement('datalist');dl.id='builderEmployeeOptions';document.body.appendChild(dl);}const options=['OPEN'].concat(state.data.employees.flatMap(e=>[e.name,`${e.name} — ${e.group}`,`${e.name} — ${e.role}`,...(e.quals||[]).map(q=>`${e.name} — ${q}`)]));dl.innerHTML=[...new Set(options)].map(v=>`<option value="${esc(v)}"></option>`).join('');}
function showAssignmentHint(input){const raw=input.value.trim();const box=$('[data-builder-results]');if(!box||!raw||raw.toUpperCase()==='OPEN')return;const name=raw.split(' — ')[0].trim();const emp=state.data.employees.find(e=>e.name.toLowerCase()===name.toLowerCase());if(!emp)return;const unavailable=state.data.unavailable.find(u=>u.day===input.dataset.day&&u.employee.toLowerCase()===emp.name.toLowerCase());const avEmployee=(state.availability?.employees||[]).find(e=>e.name.toLowerCase()===emp.name.toLowerCase());const avBlocks=(state.availability?.availability||[]).filter(a=>a.employeeId===avEmployee?.id&&a.day===input.dataset.day&&a.status!=='available');const restrictions=(state.availability?.restrictions||[]).filter(r=>r.employeeId===avEmployee?.id);const preferences=(state.availability?.preferences||[]).filter(p=>p.employeeId===avEmployee?.id);const roleOk=emp.role===input.dataset.role||emp.quals.includes(input.dataset.role)||input.dataset.role==='Dispatcher';const hint=document.createElement('div');hint.className='builder-result builder-autocomplete-hint';hint.innerHTML=`<strong>${esc(emp.name)}</strong><span>${esc(emp.group)} • ${esc(emp.role)} • ${esc(emp.quals.join(', '))}</span><span>${unavailable?'Unavailable: '+esc(unavailable.reason):avBlocks.length?'Restriction: '+esc(avBlocks.map(a=>a.source).join(', ')):'Available for this day in preview data'}${roleOk?'':' • Role warning'}${preferences.length?' • Prefers '+esc(preferences.map(p=>p.value).slice(0,2).join(', ')):''}${restrictions.length?' • '+esc(restrictions.length)+' restriction(s) on file':''}</span>`;const old=box.querySelector('.builder-autocomplete-hint');if(old)old.remove();box.prepend(hint);}
