/* Signal Labs | Signal Schedule | schedule/pages/employee/employee-portal.js | v5.1.0 */
const state={portal:null,builder:null,employeeId:null,viewMode:'employee',viewGroup:''};
const $=(s)=>document.querySelector(s);const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
Promise.all([fetch('../data/employee-portal-preview.json').then(r=>r.json()),fetch('../data/schedule-builder-sandbox.json').then(r=>r.json())]).then(([portal,builder])=>{state.portal=portal;state.builder=builder;state.employeeId=portal.selectedEmployeeId||portal.employees[0]?.id;state.viewGroup=portal.groups[0]?.id||'';render();});
function render(){renderViewbar();renderContent();}
function currentEmployee(){return state.portal.employees.find(e=>e.id===state.employeeId)||state.portal.employees[0];}
function visibleEmployeeIds(){if(state.viewMode==='employee')return [state.employeeId];const group=state.portal.groups.find(g=>g.id===state.viewGroup);return group?group.members:[state.employeeId];}
function visibleEmployees(){const ids=new Set(visibleEmployeeIds());return state.portal.employees.filter(e=>ids.has(e.id));}
function renderViewbar(){const el=$('[data-employee-viewbar]');const emp=currentEmployee();el.innerHTML=`<label><span>View As Mode</span><select data-view-mode><option value="employee">Employee</option><option value="group">Group</option><option value="role">Group / role / location / qualification / shift / pattern</option></select></label><label><span>Employee</span><select data-employee-select>${state.portal.employees.map(e=>`<option value="${esc(e.id)}" ${e.id===state.employeeId?'selected':''}>${esc(e.name)} — ${esc(e.group)}</option>`).join('')}</select></label><label><span>Group View</span><select data-group-select>${state.portal.groups.map(g=>`<option value="${esc(g.id)}" ${g.id===state.viewGroup?'selected':''}>${esc(formatGroupLabel(g))}</option>`).join('')}</select></label><div><strong>${esc(state.viewMode==='employee'?emp.name:(state.portal.groups.find(g=>g.id===state.viewGroup)?.label||'Group'))}</strong><p class="view-note">Permanent View As preview for employee, group, role, location, qualification, shift, and pattern. This remains after authentication and later gets audit logging.</p></div>`;el.querySelector('[data-view-mode]').value=state.viewMode;el.querySelector('[data-view-mode]').addEventListener('change',e=>{state.viewMode=e.target.value==='employee'?'employee':'group';render();});el.querySelector('[data-employee-select]').addEventListener('change',e=>{state.employeeId=e.target.value;state.viewMode='employee';render();});el.querySelector('[data-group-select]').addEventListener('change',e=>{state.viewGroup=e.target.value;state.viewMode='group';render();});}
function formatGroupLabel(group){const typeLabels={shiftGroup:'Shift group',role:'Role',location:'Location',qualification:'Qualification',pattern:'Pattern'};const label=group?.label||'';const type=typeLabels[group?.type]||'';return type?`${label} — ${type}`:label;}
function renderContent(){const page=document.body.dataset.employeePage||'index';if(page==='calendar')return renderCalendar();if(page==='requests')return renderRequests();if(page==='profile')return renderProfile();return renderDashboard();}
function renderDashboard(){const employees=visibleEmployees();const assignments=assignmentsFor(employees);$('[data-employee-content]').innerHTML=`<section class="schedule-card"><h2>My Schedule</h2><div class="employee-list">${assignments.slice(0,8).map(a=>`<div class="employee-item"><strong>${esc(a.day)} ${esc(a.shift)}</strong><span>${esc(a.employee)} • ${esc(a.role)}</span></div>`).join('')||empty('No assignments visible for this view.')}</div></section><aside class="schedule-card"><h2>Notifications</h2><p class="view-note">Admin users see this same employee dashboard plus admin-only tools.</p><div class="employee-list">${notificationsFor(employees).map(n=>`<div class="employee-item"><strong>${esc(n.title)}</strong><span>${esc(n.body)}</span></div>`).join('')||empty('No notifications.')}</div></aside><section class="schedule-card"><h2>My Profile / Visible Employees</h2><div class="employee-card-grid">${employees.map(employeeCard).join('')}</div></section><aside class="schedule-card"><h2>My Overtime</h2>${otList()}</aside>`;}
function renderCalendar(){const employees=visibleEmployees();const as=assignmentsFor(employees);$('[data-employee-content]').innerHTML=`<section class="schedule-card" style="grid-column:1/-1"><h2>Published Calendar Preview</h2><div class="employee-calendar">${state.builder.days.map(day=>`<div class="employee-day"><h3>${esc(day)}</h3>${as.filter(a=>a.day===day).map(a=>`<div class="employee-shift"><strong>${esc(a.shift)}</strong><br>${esc(a.employee)} • ${esc(a.role)}</div>`).join('')||'<span class="view-note">No visible shift</span>'}</div>`).join('')}</div></section>`;}
function renderRequests(){const employees=visibleEmployees();$('[data-employee-content]').innerHTML=`<section class="schedule-card"><h2>Requests</h2><div class="employee-list">${requestsFor(employees).map(r=>`<div class="employee-item"><strong>${esc(r.type)} — ${esc(r.status)}</strong><span>${esc(r.window)} • ${esc(r.hours)} hours</span></div>`).join('')||empty('No request history for this view.')}</div></section><aside class="schedule-card"><h2>Available Overtime</h2>${otList()}</aside>`;}
function renderProfile(){const employees=visibleEmployees();$('[data-employee-content]').innerHTML=`<section class="schedule-card"><h2>Profile View</h2><div class="employee-card-grid">${employees.map(employeeCard).join('')}</div></section><aside class="schedule-card"><h2>Balances</h2><div class="employee-list">${state.portal.balances.filter(b=>visibleEmployeeIds().includes(b.employeeId)).map(b=>`<div class="employee-item"><strong>${esc(b.bank)}</strong><span>${esc(b.hours)} hours</span></div>`).join('')||empty('Balances will appear here when connected.')}</div></aside>`;}
function employeeCard(e){return `<div class="employee-item"><strong>${esc(e.name)}</strong><span>${esc(e.role)} • ${esc(e.group)}</span><div class="employee-badge-row">${(e.quals||[]).map(q=>`<span class="employee-badge">${esc(q)}</span>`).join('')}</div></div>`;}
function assignmentsFor(employees){const names=new Set(employees.map(e=>e.name.toLowerCase()));return state.builder.assignments.filter(a=>names.has(String(a.employee).toLowerCase()));}
function notificationsFor(employees){const ids=new Set(employees.map(e=>e.id));return state.portal.notifications.filter(n=>ids.has(n.employeeId));}
function requestsFor(employees){const ids=new Set(employees.map(e=>e.id));return state.portal.requests.filter(r=>ids.has(r.employeeId));}
function otList(){return `<div class="employee-list">${state.portal.overtime.map(o=>`<div class="employee-item"><strong>${esc(o.title)}</strong><span>${esc(o.window)} • ${esc(o.status)}</span><span>Qualified: ${esc((o.qualified||[]).join(', '))}</span></div>`).join('')}</div>`;}
function empty(text){return `<div class="employee-item"><span>${esc(text)}</span></div>`;}
